%YAML:1.0

#Multiple thread support
multiple_thread: 0

#optimization PARAMETERS
max_solver_time: 0.07  # max solver itration time (s), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 0 # keyframe selection threshold (pixel)

evaluate_residual: 1
optimal_odometry: 1

###############################################
# laser parameters
num_of_laser: 2
n_scans: 16

# segmentation
segment_cloud: 0
horizon_scan: 1800
min_cluster_size: 5
min_line_size: 10
segment_valid_point_num: 5
segment_valid_line_num: 3
segment_theta: 0.53

# window sizes
window_size: 7
opt_window_size: 3

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 2   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Have no prior about extrinsic parameters. We will initialize and optimize around them
optimal_extrinsic: 0

body_T_laser: !!opencv-matrix
   rows: 2
   cols: 7
   dt: d
   data: [0, 0, 0, 1, 0, 0, 0,
          0, 0, 0, 1, 0, 0, 0] # qx qy qz qw px py pz
   # data 20190809
   # data: [0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000,
   #        0.345143, -0.00842792, -0.000217284, 0.938512, -0.101199, -0.756753, -0.142337] # initialization
   # data: [0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000,
   #        0.37373, -0.0002, 0.00534, 0.92751, 0.01170, -0.4840, -0.1824] # estimate
   # data 20200207
   # data: [0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000,
   #        0.46517, 0.00826, -0.0426, 0.88415, 0.04379, -0.4389, -0.6124]             
   # initialize data
   # data: [0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000,
   #        0.40092, 0.02304, -0.0507, 0.9144, -0.00772, -0.66878, -0.46053]          
   # refinement data
   # data: [0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000,
   #        0.40093, 0.00536, -0.02534, 0.91574, -0.01571, -0.47446, -0.21247]
   # iv data
   # data: [0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000,
   #        0.407, -0.002, 0.006, 0.918, -0.005, -0.450, -0.228]

#unsynchronization parameters
estimate_td: 0                      # 0 have an accurate time offset among sensors
                                    # 1 online estimate time offset among sensors

td: !!opencv-matrix                 # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
   rows: 1
   cols: 2
   dt: d
   data: [0, 0]

idx_ref: 0

cloud0_topic: "/left/velodyne_points"
cloud1_topic: "/right/velodyne_points"

laser_sync_threshold: 0.07
roi_range: 0.5
roi_range_mapping: 15

# odometry parameters
scan_period: 0.1
distance_sq_threshold: 25
nearby_scan: 2.5
distortion: 1

# movement type
planar_movement: 0

# feature corresponding paprameters
min_match_sq_dis: 1.0
min_plane_dis: 0.2

# factor
marginalization_factor: 1
point_plane_factor: 1
point_edge_factor: 1
prior_factor: 0
prior_factor_pos: 5
prior_factor_rot: 1
check_jacobian: 0

pcl_viewer: 0
pcl_viewer_normal_ratio: 10

# calibration converage parameters
n_cumu_feature: 10
eig_initial: 200
eig_thre_calib: 450
n_calib: 10

# mapping uncertainty
uncertainty_calib: !!opencv-matrix
   rows: 1
   cols: 9
   dt: d
   data: [0.01, 0.01, 0.01, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025] # rotation, translation, point

norm_threshold: 0.82

map_corner_res: 0.2
map_surf_res: 0.4
map_eig_thre: 1
#
