%YAML:1.0

#Multiple thread support
multiple_thread: 0

#optimization PARAMETERS
max_solver_time: 0.07  # max solver itration time (s), to guarantee real time
max_num_iterations: 15   # max solver itrations, to guarantee real time
keyframe_parallax: 0 # keyframe selection threshold (pixel)

evaluate_residual: 1
optimal_odometry: 1

###############################################
# laser parameters
num_of_laser: 2
n_scans: 16

# segmmentation
segment_cloud: 1
horizon_scan: 1800
min_cluster_size: 20
min_line_size: 10
segment_valid_point_num: 5
segment_valid_line_num: 3
segment_theta: 0.53

# window sizes
window_size: 5
opt_window_size: 3

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Have no prior about extrinsic parameters. We will initialize and optimize around them
optimal_extrinsic: 0

body_T_laser: !!opencv-matrix
   rows: 4
   cols: 7
   dt: d
# no prior
# qx qy qz qw px py pz
   # data: [0, 0, 0, 1, 0, 0, 0, 
   #        0, 0, 0, 1, 0, 0, 0,
   #        0, 0, 0, 1, 0, 0, 0,
   #        0, 0, 0, 1, 0, 0, 0] 
   data: [0, 0, 0, 1, 0, 0, 0, 
          0, 0, 0, 1, 0, 0, 0,
          -0.12886, 0.21263, 0.67438, 0.69527, 0, 0, 0,
          0.080047, 0.16507, -0.68757, 0.70256, 0, 0, 0]           
# manufactor
   # data: [0, 0, 0, 1, 0, 0, 0,
   #       [-0.022141, 0.06658, 0.01914, 0.99735, 0.49015, -0.041563, -0.84056,
   #       [-0.11585, 0.18957, 0.67985, 0.69889, 0.42964, 0.67832, -0.93309,
   #       [0.072775, 0.13635, -0.74163, 0.65277, 0.4746, -0.72743, -0.96377]

#unsynchronization parameters
estimate_td: 0                      # 0 have an accurate time offset among sensors
                                    # 1 online estimate time offset among sensors

td: !!opencv-matrix                 # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
   rows: 1
   cols: 4
   dt: d
   data: [0, 0, 0, 0]

idx_ref: 0

cloud_topic:
   - "/top/velodyne_points"
   - "/front/velodyne_points"
   - "/left/velodyne_points"
   - "/right/velodyne_points"

laser_sync_threshold: 0.07
roi_range: 100
roi_range_mapping: 15

# odometry parameters
scan_period: 0.1
distance_sq_threshold: 25
nearby_scan: 2.5
distortion: 0

# movement type
planar_movement: 0

# feature corresponding paprameters
min_match_sq_dis: 1.0
min_plane_dis: 0.2

# factor
marginalization_factor: 1
point_plane_factor: 1
point_edge_factor: 0
prior_factor: 0
prior_factor_pos: 5
prior_factor_rot: 1
check_jacobian: 0

pcl_viewer: 0
pcl_viewer_normal_ratio: 10

# calibration converage parameters
n_cumu_feature: 10
eig_initial: 120
eig_thre_calib: 400
n_calib: 10

# mapping 
map_corner_res: 0.2
map_surf_res: 0.4
map_eig_thre: 200

# uncertainty parameter
# translation, rotation, point (s, phi, zeta)
uct_ext: !!opencv-matrix
   rows: 4
   cols: 6
   dt: d
   data: [0, 0, 0, 0, 0, 0,
          0.0025, 0.0025, 0.0025, 0.01, 0.01, 0.01,
          0.0025, 0.0025, 0.0025, 0.01, 0.01, 0.01,
          0.0025, 0.0025, 0.0025, 0.01, 0.01, 0.01] 

uct_measurement: !!opencv-matrix
   rows: 1
   cols: 3
   dt: d
   data: [0.0025, 0.0025, 0.0025]

trace_threshold_before_mapping: 7
trace_threshold_after_mapping: 7

skip_num_odom: 1