%YAML:1.0

###############################################
#common parameters
imu: 0
num_of_cam: 2

imu_topic: ""
output_path: "/home/jjiao/catkin_ws/src/localization/M-LOAM/log/simu/"

# mloam_odom_path: "mloam_odom_with_margin.csv"
mloam_odom_path: "mloam_odom.csv"
mloam_map_path: "mloam_map.csv"
mloam_gt_path: "mloam_gt.csv"

#Multiple thread support
multiple_thread: 0

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 30            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.07  # max solver itration time (s), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.0e-4       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

###############################################
# laser parameters
num_of_laser: 2
n_scans: 16

# window sizes
window_size: 7
opt_window_size: 5

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Have no prior about extrinsic parameters. We will initialize and optimize around them
optimal_extrinsic: 0

body_T_laser: !!opencv-matrix
   rows: 2
   cols: 7
   dt: d
   # data: [0, 0, 0, 1, 0, 0, 0,
   #        0, 0, 0, 1, 0, 0, 0] # qx qy qz qw px py pz
   # simulation
   # data: [0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000,
   #        # 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000]
   #        0.342, 0.0, 0.0, 0.940, 0, -0.477, -0.220]
   data: [0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000,
          0.31, 0.0, 0.0, 0.94, 0, -0.2, 0.0]

# <!-- laser_0 to laser_1 -->
# <!-- 0.342, 0.0, 0.0, 0.940, 0, -0.477, -0.220 -->
# <!-- base_link to laser_0 -->
# <!-- -0.216 0 0 0.976 0 0.266 0.734 -->
# <!-- base_link to laser_1 -->
# <!-- 0.131 0 0 0.991 0 -0.260 0.736 -->

#unsynchronization parameters
estimate_td: 0                      # 0 have an accurate time offset among sensors
                                    # 1 online estimate time offset among sensors

td: !!opencv-matrix                 # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
   rows: 1
   cols: 2
   dt: d
   data: [0, 0]

idx_ref: 0

cloud0_topic: "/left/velodyne_points"
cloud1_topic: "/right/velodyne_points"

laser_sync_threshold: 0.07
roi_range: 0.5

# odometry parameters
scan_period: 0.1
distance_sq_threshold: 25
nearby_scan: 2.5

# movement type
planar_movement: 1

# feature corresponding paprameters
min_match_sq_dis: 1.0
min_plane_dis: 0.2

# factor
marginalization_factor: 1
point_plane_factor: 1
point_edge_factor: 1
prior_factor: 0
prior_factor_pos: 0.5
prior_factor_rot: 1
check_jacobian: 0

evaluate_residual: 1

pcl_viewer: 0
pcl_viewer_normal_ratio: 10

optimal_odometry: 1
n_cumu_feature: 10

eig_initial: 100

#
