%YAML:1.0

#common parameters
imu: 0
num_of_cam: 2

imu_topic: ""
output_path: "/home/jjiao/catkin_ws/output"

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Have no prior about extrinsic parameters. We will initialize and optimize around them

body_T_laser0: !!opencv-matrix
   rows: 1
   cols: 7
   dt: d
   # data: [0, 0, 0, 1, 0, 0, 0] # qx qy qz qw px py pz
   data: [-0.257443, 0.001306, -0.006396, 0.966271, -0.014772, 0.268227, -0.000462]

body_T_laser1: !!opencv-matrix
   rows: 1
   cols: 7
   dt: d
   # data: [0, 0, 0, 1, 0, 0, 0]
   data: [0.257476, 0.002049, 0.006198, 0.966263, 0.014772, -0.268227, 0.000462]

#Multiple thread support
multiple_thread: 0

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 30            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.08  # max solver itration time (s), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 15 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.0e-4       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

# laser parameters
num_of_laser: 2
n_scans: 16

cloud0_topic: "/left/velodyne_points"
cloud1_topic: "/right/velodyne_points"

laser_sync_threshold: 0.07
roi_range: 0.5

# odometry parameters
scan_period: 0.1
distance_sq_threshold: 25
nearby_scan: 2.5




#
